### ISSUE TITLE
AnimationWindow component draw functions

### ISSUE THREAD

**Issue by eric-reeder** [eric-reeder/24780-project#8]
You currently have the draw functions for each object contained in the AnimationWindow class, but the draw functions for the objects (mass, spring, and damper) should be contained in the draw function for that object.

**Comment by TeresaAKent** [comment]
Is there a reason i need to do it this way.  I choose to do it the other way because the functions all contain the same calculations relating to the window size which would require too much decloration over and over of it.  Would it be possible to change the main code to take in the draw function?  I was also concerned because the spring and damper classes were for only one spring/damper which messeswith my ability to  set the "0" point of the masses.  If you had a way to get around that I missed it in your code.

**Comment by eric-reeder** [comment]
So, I'm going to use the Mass object as an example because it's the easiest to understand due to it just being a box, but the same idea applies to the other objects as well. 

Almost all the information you need to draw the mass is contained in the mass object. It's member variables include it's width, height, color, and position relative to 0 (i.e. how much it has displaced from it's equilibrium position). If you called the draw function for the mass, it would draw the mass just as you want it except that it's origin would be at (0,0). This means that the only thing you need to do to draw it exactly the way you want is to make the mass.draw() function take two integers as inputs that define x and y offsets so that you can have the mass be drawn where you want it on the screen. 

In the AnimationWindow class you can have the offsets for each of the objects be defined as member variables and then you can just call the draw function for each object and pass in the offsets for that object. That way you can just use the functionality that's already in the system objects rather than redefining everything.

**Comment by TeresaAKent** [comment]
Ok I am also worried about the constat c multiplier I am using in case the distances they are traveling are too short or too long right now the constant is one but i forsee that changing in the final touches.  If you want to find what I am talking about I would comand f the word ruler (thats a comment right near the line of code I am discussing).  

My second concern is the location of the things such as the damper on the mass and spring on the mass and the force line on the mass are currently scalable so if the window size changes these variables will still be on the mass.  Although maybe setting the height location in the function might work around it.  But then we need to make sure that height location is set as a dependent on screensize and import extra variables mutliple times. 

I am thirdly concerned about the multiple states of the multiple masses and multiple springs and multiple dampers.  I am not sure how your class stores 3 seperates of those variables.  This is my biggest concern because if I do not understand how it is accesing the 3 speerate variables I really cannot finish the code. 

I still belive it might be easiest to include the spring function in the draw function and just access the values strait although there again I will need to understand how you are pulling each spring value seperatly.  Alternativly I can try and pull my information strait from the UI and the output from the ode solver.  However, if you adress  my concerns I can be persuaded to the other way.

**Comment by TeresaAKent** [comment]
If you want I could write the code I would use in the dynamic system app to call my functions just so you understand what I am proposing and see what you think

**Comment by eric-reeder** [comment]
Regarding implementing a maximum displacement, that can be solved by passing in a max displacement into the draw function, or setting the maximum displacement as a member variable in the mass object (the second one is probably a better option because, like the size of the object, it would just need to be scaled once at the beginning, see next point).

Regarding scaling, since the window size is set at the initialization of the app, you only need to set the size of the objects once. Right now they are set to constants (I just put in some arbitrary values), but you could create a setWidth() and setHeight() function that would set the size of each object based on the size of your window that would just get called once at initialization.

Regarding tracking the state of each object, each object stores info on it's own state. Just put a check in the draw function to make sure it is active before drawing.

I wrote the draw function for the mass class so you can see what I mean.

**Comment by TeresaAKent** [comment]
should be resolved
